config/routes.rb
BpsFishingTour::Application.routes.draw do

    resources :scores do
        collection { post :import }
    end
    get 'scores/angler/:id/:angler_id' => 'scores#angler'
    get 'scores/co_angler/:id/:co_angler_id' => 'scores#co_angler'
    get '/score/remove-angler' => 'scores#remove_angler'
    get 'score/remove-co-angler' => 'scores#remove_co_angler'

    # Static Page Routing
    root to: 'static_pages#home'
    %w[thanks about confirm help].each do |page|
        get page, controller: 'static_pages', action: page
    end

    get '/select_profile_picture' => 'profiles#select_profile_pic'
    post '/upload_profile_pic' => 'profiles#upload_profile_pic'
    get'/team_select_profile_picture' => 'teams#select_profile_pic'
    post '/upload_team_pic' => 'teams#upload_team_pic'
    # Profile Routing
    get '/myprofile' => 'profiles#show_current', as: 'my_profile'
    get '/profiles', to: redirect('/anglers')
    get '/profiles/completion-reminder' => 'profiles#completion_reminder'
    resources :profiles


    # Event Routing
    resources :events
    match '/events/:id/attend' => 'events#register_event', as: 'register_event', via: :post
    match '/events/:id/unattend' => 'events#unregister_event', as: 'unregister_event', via: :post
    get '/events' => 'events#index', as: 'events_path'
    get '/event-scores/:id' => 'events#event_scores', as: :event_scores, via: :get
    post '/events/:id/merge' => 'events#merge', as: :event_merge, via: :post
    # Authentication Routing
    devise_for :users, controllers: {
        registrations: 'registrations',
        confirmations: 'confirmations'
    }

    get '/join', to: redirect('/users/sign_up')

    # Team Routing
    get '/teams', to: redirect('/leaderboard')
    match '/teammate/send_invite' => 'teams/requests#send_invite', as: 'send_invite', via: :post
    match '/teammate/invite_response/:id' => 'teams/requests#respond_to_invite', as: 'invite_response', via: :get
    match '/teammate/accept_invite/:request_id' => 'teams/requests#accept_invitation', as: 'accept_invite', via: :get
    match '/teammate/reject_invite' => 'teams/requests#reject_invitation', as: 'reject_invite', via: :get

    match '/users/:id/team_invitations' => 'teams/requests#team_invitations', as: 'team_invitations', via: :get
    scope '/teams' do
        match '/requests/new' => 'teams/requests#new', via: :get
        get '/requests/invite-reminder' => 'teams/requests#invite_reminder'
    end

    resources :teams

    # Anglers Routing
    get '/anglers' => 'anglers#index'

    # Leaderboard Routing
    get '/leaderboard' => 'leaderboard#index'

    # News Routing
    get '/news' => 'news#index'
    get '/news/:year/:month/:day/:title' => 'news#story'

    # Secret Admin Routing
    get '/admin/users-report' => 'admin#users_report'
    get '/admin/users-table' => 'admin#users_table', as: 'user_report'
    get '/admin/team-table' => 'admin#team_table', as: 'team_table'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    validates :first_name, :last_name, :city, :street_address, :state, :presence => true, :on => :update
    validates_format_of :first_name, :last_name, :city, :street_address, :state, :zip, :allow_blank => true,
        without: /\A[ \t]+|[ \t]+\z/,
        on: :update,
        message: "- please remove trailing and/or leading whitespace"

    picture_options = {
        styles: {
            medium: '300x300>}',
            teamP: '96x96#',
            tour: '80x80#'
        }
    }
    picture_options.update({
        storage: :s3,
        s3_credentials: "#{::Rails.root}/config/aws.yml"
    }) if ENABLE_S3

  has_attached_file :picture, picture_options
  acts_as_deactivatable


    def self.directory
        names = Profile.all.reject{|profile| profile.first_name.blank? || profile.last_name.blank?}.sort{|x,y|
            x.last_name.to_s.strip.capitalize <=> y.last_name.to_s.strip.capitalize }
            .map { |profile|
            {
                name: "#{profile.last_name.to_s.nameize}, #{profile.first_name.to_s.nameize}",
                id: profile.id,
            }
        }
        names.select { |name| name[:name] !~ /^,/ }.group_by {|name| name[:name][0] }
    end

    def shirt_size
        case self.shirt
        when "1"
            "-"
        when "2"
            "XS"
        when "3"
            "S"
        when "4"
            "M"
        when "5"
            "L"
        when "6"
            "XL"
        when "7"
            "XXL"
        when "8"
            "XXXL"
        end
    end

    def full_name(arrangement = 'f l')
        if self.first_name.nil? || self.last_name.nil?
            return nil
        end
        if arrangement == 'f l'
            "#{self.first_name.nameize} #{self.last_name.nameize}"
        else
            "#{self.last_name.to_s.nameize}, #{self.first_name.to_s.nameize}"
        end
    end

    def deactivate
        self.user.update_attribute('deactivated_at', Time.now) if self.user.deactivated_at.nil?
        self.update_attribute('deactivated_at', Time.now) if self.user.deactivated_at.nil?
    end

    def activate
        self.user.update_attribute('deactivated_at', nil) unless self.user.deactivated_at.nil?
        self.update_attribute('deactivated_at', nil) unless self.user.deactivated_at.nil?
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:update, :destroy]

    # GET /profiles
    def index
        @profiles = Profile.all
    end

    # GET /profiles/1
    def show
        @profile = Profile.find(params[:id])
        @user = @profile.user
        @teammate = @user.teammate
        @team = @user.my_team
        @events = @team ? @team.events : nil
        redirect_to my_profile_path if user_signed_in? && @profile.id == current_user.profile.id
        @can_register = @profile.user.teams.size > 0
        @is_current_user = false
        @board = Leaderboard.qualified_teams
    end

    # GET /myprofile
    def show_current
        @user = current_user
        @teammate = @user.teammate
        @can_register = current_user.teams.size > 0
        @new_user = current_user.profile.valid? ? false : true
        current_user.profile.errors.clear

        #@new_user = true if params[:edit] && params[:edit] = true
        current_user.create_profile unless current_user.profile
        @profile = current_user.profile
        @team = current_user.my_team
        @events = @team ? @team.events : nil
        @is_current_user = true
        @board = Leaderboard.qualified_teams
    end

    # GET /profiles/new
    def new
        @profile = Profile.new
    end

    # GET /profiles/1/edit
    def edit
        @profile = current_user.profile
        @edit_view = true
    end

    def select_profile_pic
        unless current_user.nil? || !current_user.profile
            @profile = current_user.profile
        else
            flash.clear
            flash.now[:notice] = "Please login to upload your photo"
            redirect_to '/'
        end
    end

    def upload_profile_pic
        @profile = current_user.profile
        @profile.attributes = profile_params if params[:profile]
        if @profile.save(validate: false) && params[:profile]
            redirect_to my_profile_path(:tab => 'team'), notice: "Your Profile picture has been uploaded!"
        else
            flash.clear
            flash.now[:notice] = "Uh oh! There seems to be an issue with uploading your image!"
            render :select_profile_pic
        end
    end

    # POST /profiles
    def create
        @profile = Profile.new(profile_params)
        @profile.user_id = current_user.id

        if @profile.save
            redirect_to requests_new_path, notice: 'Thanks for creating your profile, go ahead and set up a team!'
        else
            render action: 'new'
        end
    end

    # PATCH/PUT /profiles/1
    def update
        @team = current_user.teams.first

        respond_to do |format|
            if @profile.update(profile_params)
                if @team.nil?
                    format.html { redirect_to requests_new_path}
                else
                    format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
                    format.json { respond_with_bip(@profile) }
                end
            else
                if(current_user.teams.size > 0)
                    @can_register = true
                else
                    @can_register = false
                end

                path = URI::parse(request.referrer).path
                @showTab = true
                flash.now[:error] = "We could not update your profile!"
                # raise 
                # return render text: params[:id] == @profile.id.to_s
                unless params[:from_edit]
                    @user = @profile.user
                    @new_user = current_user.profile.valid? ? false : true
                    format.html { render action: 'show_current' }
                else
                    format.html { render action: 'edit' }
                end
            end
        end
    end

    # DELETE /profiles/1
    def destroy
        @profile.destroy
        redirect_to profiles_url
    end

    def completion_reminder
        ProfileMailer.completion_reminder(params[:email]).deliver
        render text: 'Reminders sent.'
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_profile
            @profile = Profile.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def profile_params
            params.require(:profile).permit(:user_id, :first_name, :last_name, :street_address, :suite, :city, :state, :zip, :phone, :ext, :shirt, :picture, :outdoor_rewards_number, :status)
        end
end

app/views/profiles/_form.html.erb
<div class="teamRegContainer">
    <div class="topGreenBanner">
        <p>Team Registration</p>
    </div>

    <%= form_for(@profile, url: profile_path(@profile.id, from_edit: @edit_view), method: "patch") do |f| %>
    <div class="teamRegContainerForm">
            <% if @profile.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

                    <ul>
                        <% @profile.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="regTopText">
                <h3>Register Your Team</h3>
                <p>By registering for a Team Membership, you'll unlock the full benifits of the tour, including opportunities to win exciting prize and to qualify for regional and national championship events.</p>
                <h2><%= link_to 'Learn more about Team Memberships.', about_path %></h2>
            </div>
            <h3>Account Information</h3>
            <div class="divideLine"></div>
            <div class="half">
                <%= f.label :first_name %>
                <%= f.text_field :first_name %>
            </div>
            <div class="half">
                <%= f.label :last_name %>
                <%= f.text_field :last_name %>
            </div>
            <div class="full">
                <%= f.label :street_address %>
                <%= f.text_field :street_address %>
            </div>
            <div class="third">
                <%= f.label :suite %>
                <%= f.text_field :suite %>
            </div>
            <div class="two thirds">
                <%= f.label :city %>
                <%= f.text_field :city %>
            </div>
            <div class="thirds">
                <%= f.label :state %>
                <%= f.text_field :state %>
            </div>
            <div class="two thirds">
                <%= f.label :zip %>
                <%= f.text_field :zip %>
            </div>
            <div class="two thirds">
                <%= f.label :phone %>
                <%= f.text_field :phone %>
            </div>
            <div class="third">
                <%= f.label :ext %>
                <%= f.text_field :ext %>
            </div>
            <div class="third">
                <%= f.label :shirt %>
                <%= f.select :shirt, [['Select Size', 1], ['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL'], ['XXXL', 'XXXL']] %>
            </div>
            <div class="full">
                <%= f.label :outdoor_rewards_number %>
                <%= f.password_field :outdoor_rewards_number %>
                <p><%= link_to "I don't have an Outdoor Rewards Number. Sign me up!", 'https://www.basspro.com/webapp/wcs/stores/servlet/UserRegistrationForm?catalogId=10051&langId=-1&storeId=10151&krypto=oeELImlnMXmlNbMTLcfsXdqvZZycRZJfw9To%2FJ80jY6Dxwluyf%2Fz7XpsYcectS%2BItRbPzIxxvnw%3D&ddkey=http:UserRegistrationForm', target: '_blank' %></p>
            </div>
    </div>
            <div class="actions">
                <%= link_to 'Back', profiles_path %>
                <%= f.submit 'Continue' %>
            </div>
        <% end %>
</div>
<div class="formSpace"></div>

app/views/profiles/_my_events.html.erb
<div class="teamEvents">
    <div class="topDarkBrown">
        <%= image_tag 'iconCal.png', class: 'iconSmallEvents', alt: 'Calendar icon' %>
        <h2>My Events <div class="seeAll"><%= link_to 'See all events', events_path %></div></h2>
    </div>
    <table>
        <tbody>
            <tr class="topLightBrown">
                <th class="thLeft">Date</th>
                <th class="thMiddle">Event Title</th>
                <th class="thRight">Status</th>
            </tr>
        </tbody>
    </table>
    <div class="table-container">
        <% if @team.nil? %>
            <p>This user is not yet part of a team, and can't attend events.</p>
        <% elsif @events.nil? %>
            <p>This team isn't signed up for any events yet.</p>
        <% else %>
            <table>
                <tbody>
                    <% @events.each do |event| %>
                        <tr class="<%= cycle("odd", "even") %>">
                            <td class="tdDate"><%= event.date.to_date %></td>
                            <td class="tdName"><%= event.date < Time.now && !event.scores.empty? ? link_to(event.name, event_scores_path(event.id)) : event.name %></td>
                            <td class="tdStatus"><%= add_status(@team, event) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div><!-- table container -->
</div>

app/views/profiles/_tab_team_pro.html.erb
<div id="tab2" class="tab-pane">
    <div class="myTourCont">
        <div class="teamContRight">
            <div class="myCont">
                <%= image_tag 'iconBoat.png', class: 'tourBoat', alt: 'Boat Icon' %>
                <h3>Tournament Boat:</h3>

                <% if @team && @is_current_user %>
                    <%= link_to(image_tag('iconWriteLight.png', class: 'writeIcon', alt: 'Write Icon'),'#', :id => 'boat_description') %>
                    <p><%= best_in_place @team, :boat_description, nil: "Tell us what boat your team will be using for the Bass Pro Fishing Tour here.", :activator => '#boat_description' %></p>
                <% else %>
                    <p>No boat info available.</p>
                <% end %>

            </div>
            <div class="divideLine"></div>
            <div class="myCont no">
                <%= image_tag 'iconLure.png', class: 'tourLure', alt: 'Lure Icon' %>
                <h3>Favorite Gear:</h3>

                <% if @team && @is_current_user %>
                    <%= link_to(image_tag('iconWriteLight.png', class: 'writeIcon', alt: 'Write Icon'),'#',:id => 'favorite_gear') %>
                    <p><%= best_in_place @team, :favorite_gear, nil: "Share your favorite gear here or the equipment you have had the best luck with!",:activator => '#favorite_gear'%></p>
                <% else %>
                    <p>No favorite gear available.</p>
                <% end %>

            </div>
            <div class="divideLine"></div>
            <div class="myCont">

                <% if @user.teammate %>
                    <%= drop_profile_teammate_pic(@user.teammate, "tourPerson", :tour, "Person Icon") %>
                <% end %>

               <!--  <% if @is_current_user %>
                    <%= image_tag 'iconWriteLight.png', class: 'writeIcon', alt: 'Write Icon' %>
                <% end %> -->

                <% if @teammate %>
                    <h3>Teammate: <%= @teammate.full_name ? link_to(@teammate.full_name.titleize, profile_path(@teammate.profile))  : "Your Teammate" %></h3>
                    <p><%= @teammate.profile.status || " " %></p>
                <% else %>
                    <h3>Angler Teammate</h3>
                    <p>This information will propagate once a teammate has completed the registration process. </p>
                <% end %>

            </div>
        </div>

        <div class="teamContLeft">
            <% if @is_current_user %>
            <%= link_to select_profile_picture_path, class: "smallPicButton" do %>
            <% end %>

            <%= link_to team_select_profile_picture_path, class: "bigPicButton" do %>
            <% end %>
        <% end %>
            <div class="cutOutContainerLeft">
                <div class="cutOutLeft">
                    <div class="cutTeamLeft"></div>
                    <div class="cutTeamMiddle"><%= image_tag 'cutTourV.png', class: 'cutTeamV', alt: 'Cut Out' %></div>
                    <div class="cutTeamRight"></div>
                </div>
                <%= team_picture(@user.my_team, 'teamPic', :teampro, 'Team Picture') %>
                <div class="cutOutTextTeam">
                    <h2><%= @profile.user.full_name  || "Angler Profile" %></h2>
                    <p><%= @profile.status || " " %></p>
                </div>
            </div>

            <%= image_tag 'iconManFish.png', class: 'manFishLeft', alt: 'Man Fish' %>
            <div class="manFishTextLeft"><p>Upload a Team Photo Here</p></div>
            <div class="picBoxContainerLeft">
                <div class="picBoxTeam">
                    <% unless @team && @team.team_picture.exists? %>
                        <div class="teamDot">
                            <%= image_tag 'teamDot.png', alt: 'Doted' %>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="teamContLeftBot">
                <% if @profile.picture.exists? %>
                   <%= image_tag @profile.picture.url(:teamP), class: 'teamPerson', alt: 'Person Icon' %>
                <% else %>
                   <%= image_tag 'iconPersonFull.png', class: 'teamPerson', alt: 'Person Icon' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/profiles/_team_pro_tab.html.erb
<div id="tab2" class="tab-pane <%= "active" if params[:tab] && params[:tab] == 'team' %>">
    <div class="myTourCont">
        <div class="teamContRight half">
            <div class="myCont">
                <%= image_tag 'iconBoat.png', class: 'tourBoat', alt: 'Boat Icon' %>
                <h3>Tournament Boat:</h3>

                <% if @team && @is_current_user %>
                    <%= link_to(image_tag('iconWriteLight.png', class: 'writeIcon', alt: 'Write Icon'),'#', :id => 'boat_description') %>
                    <p><%= best_in_place @team, :boat_description, nil: "Tell us what boat your team will be using for the Bass Pro Fishing Tour here.", :activator => '#boat_description' %></p>
                <% else %>
                    <p>No boat info available.</p>
                <% end %>

            </div>
            <div class="divideLine"></div>
            <div class="myCont no">
                <%= image_tag 'iconLure.png', class: 'tourLure', alt: 'Lure Icon' %>
                <h3>Favorite Gear:</h3>

                <% if @team && @is_current_user %>
                    <%= link_to(image_tag('iconWriteLight.png', class: 'writeIcon', alt: 'Write Icon'),'#',:id => 'favorite_gear') %>
                    <p><%= best_in_place @team, :favorite_gear, nil: "Share your favorite gear here or the equipment you have had the best luck with!",:activator => '#favorite_gear'%></p>
                <% else %>
                    <p>No favorite gear available.</p>
                <% end %>

            </div>
            <div class="divideLine"></div>
            <div class="myCont">

                <% if @user.teammate %>
                    <%= drop_profile_teammate_pic(@user.teammate, "tourPerson", :tour, "Person Icon") %>
                <% else %>
                    <%= image_tag 'iconPersonSmall.png', class: "tourPerson" %>
                <% end %>

                <% if @teammate %>
                    <h3>Teammate: <%= @teammate.full_name ? link_to(@teammate.full_name.titleize, profile_path(@teammate.profile,:tab => 'team'))  : "Your Teammate" %></h3>
                    <p><%= @teammate.profile.status || " " %></p>
                <% else %>
                    <h3>Angler Teammate</h3>
                    <p>This information will propagate once a teammate has completed the registration process. </p>
                <% end %>

            </div>
        </div>

        <div class="teamContLeft half">
            <div class="cutOutContainerLeft half">
                <div class="cutOutLeft">
                    <div class="cutTeamLeft"></div>
                    <div class="cutTeamMiddle"><%= image_tag 'cutTourV.png', class: 'cutTeamV', alt: 'Cut Out' %></div>
                    <div class="cutTeamRight"></div>
                </div>
                <% if @is_current_user %>
                    <%= link_to team_select_profile_picture_path, class: "bigPicButton" do %>
                    <% end %>
                <% end %>
                <%= team_picture(@user.my_team, 'teamPic', :teampro, 'Team Picture') %>
                <div class="cutOutTextTeam">

                    <% if @is_current_user %>
                        <%= link_to select_profile_picture_path, class: "smallPicButton" do %>
                            <% if @profile.picture.exists? %>
                               <%= image_tag @profile.picture.url(:teamP), class: "teamPerson", alt: 'Person Icon' %>
                            <% else %>
                               <%= image_tag 'iconPersonFull.png', class: "teamPerson #{'pulse' if user_signed_in? && @profile == current_user.profile}", alt: 'Person Icon' %>
                            <% end %>
                        <% end %>
                    <% else %>
                    <div class="smallPicButton">
                        <% if @profile.picture.exists? %>
                           <%= image_tag @profile.picture.url(:teamP), class: "teamPerson", alt: 'Person Icon' %>
                        <% else %>
                           <%= image_tag 'iconPersonFull.png', class: "teamPerson #{'pulse' if user_signed_in? && @profile == current_user.profile}", alt: 'Person Icon' %>
                        <% end %>
                    </div>
                    <% end %>

                    <div class="teamInfo">
                        <h2><%= @profile.user.full_name  || "Angler Profile" %></h2>
                        <p><%= @profile.status || " " %></p>
                        <% unless @profile.picture.exists? %>
                            <p class="profPicAlert <%= '' if user_signed_in? && @profile == current_user.profile %>"><a href="<%= select_profile_picture_path %>"><%= '<< Upload a Profile Picture' if user_signed_in? && @profile == current_user.profile %> </a></p>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="picBoxContainerLeft">
            <% unless @team && @team.team_picture.exists? %>
                <%= image_tag 'iconManFish.png', class: 'manFishLeft', alt: 'Man Fish' %>
                <div class="manFishTextLeft"><p class='<%= '' if user_signed_in? && @profile == current_user.profile %>'><%= user_signed_in? && @profile == current_user.profile ? "Upload a Team Photo Here" : "No Team Photo" %></p></div>
                <% end %>
                <% unless @team && @team.team_picture.exists? %>
                    <div class="picBoxTeam">
                        <div class="teamDot">
                            <%= image_tag 'teamDot.png', alt: 'Doted' %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/profiles/_tour_tab_noevents.html.erb
<% if @is_current_user %>
    <!-- THIS NEEDS HELP -->
    <p>Sign up to fish in Tour Events, then check back to track your performance.</p>
<% else %>
    <% if @user.events.count == 0 %>
    <p><%= @profile.first_name %> hasn't attended any events yet.  Check back later for their rankings.</p>
    <% else %>
    <% past_events = @user.events.where("date < ?", Date.today) %>
    <p><%= @profile.first_name %> has attended <%= pluralize(past_events.count, "event") %>.  Check back later for their rankings.</p>
    <% end %>
<% end %>

<div class="tour-progress">
    <p>5 events needed to qualify</p>
    <%= image_tag 'icons/fish.png', alt: 'One Event' %>
    <%= image_tag 'icons/fish.png', alt: 'Two Events' %>
    <%= image_tag 'icons/fish.png', alt: 'Three Events' %>
    <%= image_tag 'icons/fish.png', alt: 'Four Events' %>
    <%= image_tag 'icons/fish.png', alt: 'Five Events' %>
</div>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Street address</th>
      <th>Suite</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Ext</th>
      <th>Shirt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.street_address %></td>
        <td><%= profile.suite %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= profile.zip %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.ext %></td>
        <td><%= profile.shirt %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/select_profile_pic.html.erb
<div class="teamRegContainer">
    <div class="topGreenBanner">
        <p>Upload A Profile Picture</p>
    </div>

    <%= form_for @profile, :url => upload_profile_pic_path, :html => { :multipart => true }, method: "post" do |form| %>

        <div class="teamRegContainerForm">
            <% if @profile.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

                    <ul>
                        <% @profile.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
                <div class="regTopText">
                    <h3>Upload a Picture of that Mug!</h3>
                    <div class="divideLine"></div>
                    <ul>
                        <li>This photo can be edited from your profile page.</li>
                        <li>Say Cheese.</li>
                    </ul>
                </div>
                <%= form.file_field :picture %>

        </div>
        <div class="actions">
            <%= link_to :back, my_profile_path  %>
            <%= submit_tag :continue, value: 'Continue', :disabled => 'disabled', class: 'disabled' %>
        </div>
    <% end %>

</div>

app/views/profiles/show.html.erb
<%= render "shared/ads_bps" %>

<div class="tabContBackground">
    <div class="tabContainer">
        <ul class="nav nav-tabs" id="myTabs">
            <li class="<%= "active" unless params[:tab] && (params[:tab] == 'team' || params[:tab] == 'account') %>">
                <a data-toggle="tab" href="#tab1">
                    <div class="tabIconContainer">
                        <%= image_tag 'iconFishTab.png', id: 'fishSolo', class: 'iconSmall', alt: 'Fish Icon' %>
                        <div class="tabText">Tour</div>
                    </div>
                </a>
            </li>
            <li class="<%= "active" if params[:tab] && params[:tab] == 'team' %>">
                <a data-toggle="tab" href="#tab2">
                    <div class="tabIconContainer">
                        <%= image_tag 'iconPerson.png', class: 'iconSmall', alt: 'Person Icon' %>
                        <div class="tabText">Team Profile</div>
                    </div>
                </a>
            </li>
        </ul>
        <div class="tabbable">
            <div class="tab-content">
                <%= render "tour_tab" %>
                <%= render "team_pro_tab" %>
            </div>
        </div>

        <script type="text/javascript">
            $("#accountOn").on("click", function(event){
                if(($(this).attr("class")) != "active"){
                    $(".tabMidLeftCont, .tabMidRightCont").hide();
                }
            });
            $(".nav-tabs li").on("click", function(event){
                if((($(this).attr("id")) != "accountOn")){
                    $(".tabMidLeftCont, .tabMidRightCont").show();
                }
            });

            $(".nav-tabs li").on("click", function(event){
                if(($(this).attr("class")) != "accountOn"){
                    $(".adImg2, .adImg3, .adImg4").hide();
                }
            });
            $("#accountOn").on("click", function(event){
                if((($(this).attr("id")) != "active")){
                    $(".adImg2, .adImg3").show();
                }
            });
        </script>

        <div class="tabMiddleContainer">
            <div class="tabMidLeftCont">
                <%= render 'my_events', :locals => { :profile => @profile } %>
            </div>

            <div class="tabMidRightCont">
                <div class="leaderboard">
                    <div class="topBlue">
                        <%= image_tag 'iconGlobe.png', class: 'iconSmallEvents', alt: 'Icon' %>
                        <h2><%= link_to 'Leaderboard', leaderboard_path %></h2>
                    </div>
                    <%= render 'leaderboard/team_scores_small' %>
                </div>
                <div class="myRegion">
                    <div class="topGreen">
                        <%= image_tag 'iconMed.png', class: 'iconSmallEvents', alt: 'Icon' %>
                        <h2><%= link_to 'My Region', events_path %></h2>
                    </div>
                    <div class="bottomGreyFlat"><%= link_to 'Events in my region', events_path %></div>
                </div>
            </div>
        </div>
    </div>
</div>