config/routes.rb
BpsFishingTour::Application.routes.draw do

    resources :scores do
        collection { post :import }
    end
    get 'scores/angler/:id/:angler_id' => 'scores#angler'
    get 'scores/co_angler/:id/:co_angler_id' => 'scores#co_angler'
    get '/score/remove-angler' => 'scores#remove_angler'
    get 'score/remove-co-angler' => 'scores#remove_co_angler'

    # Static Page Routing
    root to: 'static_pages#home'
    %w[thanks about confirm help].each do |page|
        get page, controller: 'static_pages', action: page
    end

    get '/select_profile_picture' => 'profiles#select_profile_pic'
    post '/upload_profile_pic' => 'profiles#upload_profile_pic'
    get'/team_select_profile_picture' => 'teams#select_profile_pic'
    post '/upload_team_pic' => 'teams#upload_team_pic'
    # Profile Routing
    get '/myprofile' => 'profiles#show_current', as: 'my_profile'
    get '/profiles', to: redirect('/anglers')
    get '/profiles/completion-reminder' => 'profiles#completion_reminder'
    resources :profiles


    # Event Routing
    resources :events
    match '/events/:id/attend' => 'events#register_event', as: 'register_event', via: :post
    match '/events/:id/unattend' => 'events#unregister_event', as: 'unregister_event', via: :post
    get '/events' => 'events#index', as: 'events_path'
    get '/event-scores/:id' => 'events#event_scores', as: :event_scores, via: :get
    post '/events/:id/merge' => 'events#merge', as: :event_merge, via: :post
    # Authentication Routing
    devise_for :users, controllers: {
        registrations: 'registrations',
        confirmations: 'confirmations'
    }

    get '/join', to: redirect('/users/sign_up')

    # Team Routing
    get '/teams', to: redirect('/leaderboard')
    match '/teammate/send_invite' => 'teams/requests#send_invite', as: 'send_invite', via: :post
    match '/teammate/invite_response/:id' => 'teams/requests#respond_to_invite', as: 'invite_response', via: :get
    match '/teammate/accept_invite/:request_id' => 'teams/requests#accept_invitation', as: 'accept_invite', via: :get
    match '/teammate/reject_invite' => 'teams/requests#reject_invitation', as: 'reject_invite', via: :get

    match '/users/:id/team_invitations' => 'teams/requests#team_invitations', as: 'team_invitations', via: :get
    scope '/teams' do
        match '/requests/new' => 'teams/requests#new', via: :get
        get '/requests/invite-reminder' => 'teams/requests#invite_reminder'
    end

    resources :teams

    # Anglers Routing
    get '/anglers' => 'anglers#index'

    # Leaderboard Routing
    get '/leaderboard' => 'leaderboard#index'

    # News Routing
    get '/news' => 'news#index'
    get '/news/:year/:month/:day/:title' => 'news#story'

    # Secret Admin Routing
    get '/admin/users-report' => 'admin#users_report'
    get '/admin/users-table' => 'admin#users_table', as: 'user_report'
    get '/admin/team-table' => 'admin#team_table', as: 'team_table'
end

app/models/score.rb
class Score < ActiveRecord::Base
    after_update :score_check

    def self.import(file, event)
        CSV.foreach(file.path, headers: true, encoding: 'utf-8') do |row|
            score = row.to_hash
            score[:event_id] = event
            score.delete(nil)
            Score.create score
        end
    end

    # From the about page:
    #
    # * "1 point will be awarded for 1st place, 2 points for second,
    #   etc. down to 50 points."
    # * "Anglers finishing 50th place and below will receive 50 points."
    def points
        return self.position unless self.position > 50
        return 50
    end

    def team_check
        unless self.angler_id.blank? || self.co_angler_id.blank?
            # Get correct team
            team = Team.all.select { |team| team.users.count == 2 && team.users.first.id == self.angler_id && team.users.last.id == self.co_angler_id}.concat(Team.all.select{|team| team.users.count == 2 &&
            team.users.first.id == self.co_angler_id && team.users.last.id == self.angler_id}).uniq.first
            self.update_column("team_id", team.id.to_i) unless team.nil?
        end
    end

    def event_check
        unless self.team_id.blank?
            self.team.events << self.event unless self.team.events.include?(self.event)
        end
    end

    def score_check
        team_check
        event_check
    end

    validates :position, :event_id, :presence => true

    belongs_to :team
    belongs_to :event
    belongs_to :user
    belongs_to :angler_user, foreign_key: "angler_id", :class_name => "User"
    belongs_to :co_angler_user, foreign_key: "co_angler_id", :class_name => "User"


end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  layout 'bare'

  http_basic_authenticate_with name: 'Group360', password: 'scoreimport'

  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
    @events = Event.all
    @profiles = Profile.all

    if params[:event_id]
        @event = Event.find(params[:event_id])
    else
        redirect_to "/scores/?event_id=#{Event.all.first.id}"
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
    @events = Event.all
  end

  # GET /scores/1/edit
  def edit
    @events = Event.all
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  def import
    Score.import(params[:file], params[:event])
    redirect_to "/scores?event_id=#{params[:event]}", notice: 'Added scores'
  end

  def angler
    Score.update params[:id], angler_id: params[:angler_id]
    redirect_to :back, notice: "Angler set to #{User.find(params[:angler_id]).full_name}"
  end

  def co_angler
    Score.update params[:id], co_angler_id: params[:co_angler_id]
    redirect_to :back, notice: "Co-Angler set to #{User.find(params[:co_angler_id]).full_name}"
  end

  def remove_angler
    #return render text: params
    Score.update params[:id], angler_id: nil
    redirect_to :back, notice: "Angler removed"
  end

  def remove_co_angler
    Score.update params[:id], co_angler_id: nil
    redirect_to :back, notice: "Co-Angler removed"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:event_id, :position, :angler, :angler_rewards, :co_angler, :co_angler_rewards, :weight, :bf, :hp)
    end
end

app/views/scores/_form.html.erb
<style type="text/css">
.edit_score .field {
        margin-bottom: 10px;
}
</style>

<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.select :event_id, options_from_collection_for_select(Event.all, 'id', 'name_and_date') %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :angler %>
    <%= f.text_field :angler, :autocomplete=>"off", :data=>{:provide=>"typeahead", :source=>Profile.all.reject{|profile| profile.first_name.blank? || profile.last_name.blank?}.map{|profile| profile.full_name.upcase}} %>
  </div>
  <div class="field">
    <%= f.label :angler_rewards %>
    <%= f.text_field :angler_rewards %>
  </div>
  <div class="field">
    <%= f.label :co_angler %>
    <%= f.text_field :co_angler, :autocomplete=>"off", :data=>{:provide=>"typeahead", :source=>Profile.all.reject{|profile| profile.first_name.blank? || profile.last_name.blank?}.map{|profile| profile.full_name.upcase}} %>
  </div>
  <div class="field">
    <%= f.label :co_angler_rewards %>
    <%= f.text_field :co_angler_rewards %>
  </div>
  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :bf %>
    <%= f.text_field :bf %>
  </div>
  <div class="field">
    <%= f.label :hp %>
    <%= f.text_field :hp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<div class="navbar well">
    <%= link_to "&larr; Back to Event".html_safe, :back %>
</div>
<div class="container">
<h1>Editing Score #<%= @score.id %></h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>
</div>

app/views/scores/index.html.erb
<style type="text/css">
.city-events {
    clear: both;
    margin: 5px 0;
    height: 40px;
    line-height: 40px;
    border-bottom: 1px dotted #999;
    padding-bottom: 5px;
}
.city-events:last-child{
    border-bottom: none;
}
.city-name {
    float:left;
    vertical-align: middle;
    font-size: 120%;
}
</style>
<div class="container" style="width:90%;">
<h1>Listing scores</h1>

<nav>
    <ul>
        <% event_names = @events.group_by{|event| event.name } %>
        <% event_names.each_key do |name| %>
            <div class="city-events">
                <p class="city-name"><%= name %>:</p>
                <ul class="inline city-event-list">
                <% event_names[name].each do |event| %>
                    <% if params[:event_id].to_i == event.id %>
                    <li><%= link_to "#{event.date.strftime("%B %d, %Y")} (#{event.id})", "/scores?event_id=#{event.id}", class: "btn disabled", title: "This is the current event." %></li>
                    <% else %>
                    <li><%= link_to "#{event.date.strftime("%B %d, %Y")} (#{event.id})", "/scores?event_id=#{event.id}", class: "btn" %></li>
                    <% end %>


                <% end %>
                </ul>
            </div>
        <% end %>
    </ul>
</nav>

<h2>Event: #<%= @event.id %> <%= @event.name %></h2>
<% unless @event.possible_duplicates.empty? %>
<div class="alert">
    <p class="lead">There can be only one.</p>
<p>You may have a duplicate of this event. Use the form below to merge events together.</p>
<%= form_tag "/events/#{@event.id}/merge", class: "form form-inline" do %>
<%= select_tag :merge_event_id, options_from_collection_for_select(@event.possible_duplicates, 'id', 'name_and_date') %>
<%= submit_tag 'Merge', class: "btn btn-info" %>
<% end %>
</div>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Position</th>
      <th>Angler (ID#)</th>
      <th>Angler rewards</th>
      <th>Co angler (ID#)</th>
      <th>Co angler rewards</th>
      <th>Weight</th>
      <th>Bf</th>
      <th>Hp</th>
      <th>Link Angler</th>
      <th>Link Co-Angler</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.select{ |score| score.event_id == @event.id }.sort { |x, y| x.position <=> y.position }.each do |score| %>
      <tr>
        <td><%= score.position %></td>
        <td><%= "#{score.angler} <b>(#{score.angler_id})</b>".html_safe %></td>
        <td><%= score.angler_rewards %></td>
        <td><%= "#{score.co_angler} <b>(#{score.co_angler_id})</b>".html_safe %></td>
        <td><%= score.co_angler_rewards %></td>
        <td><%= score.weight %></td>
        <td><%= score.bf %></td>
        <td><%= score.hp %></td>
        <td>
            <% first_name_matches = @profiles.where('lower(first_name) =?', score.angler.split.first.downcase) unless score.angler.nil? %>
            <% unless first_name_matches.nil? || first_name_matches.empty? %>
                <strong>First name matches:</strong><br>
                <% first_name_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).angler_id == angler.user.id %>
                    <%= score.angler_id == angler.user.id ? link_to("#{angler.first_name} #{angler.last_name}", "/score/remove-angler?id=#{score.id}") : link_to("#{angler.first_name} #{angler.last_name}", "/scores/angler/#{score.id}/#{angler.user.id}")  %><br>
                <% end %>
            <% end %>
            <% last_name_matches = @profiles.where('lower(last_name) =?', score.angler.split.last.downcase) unless score.angler.nil? %>
            <% unless last_name_matches.nil? || last_name_matches.empty? %>
                <strong>Last name matches:</strong><br>
                <% last_name_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).angler_id == angler.user.id %>
                    <%= score.angler_id == angler.user.id ? link_to("#{angler.first_name} #{angler.last_name}", "/score/remove-angler?id=#{score.id}") : link_to("#{angler.first_name} #{angler.last_name}", "/scores/angler/#{score.id}/#{angler.user.id}") %><br>
                <% end %>
            <% end %>
            <% outdoor_matches = @profiles.where(outdoor_rewards_number: score.angler_rewards) %>
            <% if !outdoor_matches.empty? && score.angler_rewards.present? %>
                <strong>Outdoor Rewards matches:</strong><br>
                <% outdoor_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).angler_id == angler.user.id %>
                    <%= score.angler_id == angler.user.id ? link_to("#{angler.first_name} #{angler.last_name}", "/score/remove-angler?id=#{score.id}") : link_to("#{angler.first_name} #{angler.last_name}", "/scores/angler/#{score.id}/#{angler.user.id}") %><br>
                <% end %>
            <% end %>
        </td>
        <td>
            <% first_name_matches = @profiles.where('lower(first_name) =?', score.co_angler.split.first.downcase) if score.co_angler.present? %>
            <% unless first_name_matches.nil? ||first_name_matches.empty? %>
                <strong>First name matches:</strong><br>
                <% first_name_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).co_angler_id == angler.user.id %>
                    <%= score.co_angler_id == angler.user.id ? link_to("#{angler.first_name} #{angler.last_name}", "/score/remove-co-angler?id=#{score.id}") : link_to("#{angler.first_name} #{angler.last_name}", "/scores/co_angler/#{score.id}/#{angler.user.id}") %><br>
                <% end %>
            <% end %>
            <% last_name_matches = @profiles.where('lower(last_name) = ?', score.co_angler.split.last.downcase) unless score.co_angler.blank? %>
            <% unless last_name_matches.nil? || last_name_matches.empty? %>
                <strong>Last name matches:</strong><br>
                <% last_name_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).co_angler_id == angler.user.id %>
                    <%= score.co_angler_id == angler.user.id ? link_to("#{angler.first_name} #{angler.last_name}", "/score/remove-co-angler?id=#{score.id}") : link_to("#{angler.first_name} #{angler.last_name}", "/scores/co_angler/#{score.id}/#{angler.user.id}") %><br>
                <% end %>
            <% end %>
            <% outdoor_matches = @profiles.where(outdoor_rewards_number: score.co_angler_rewards) %>
            <% if !outdoor_matches.empty? && score.co_angler_rewards.present? %>
                <strong>Outdoor Rewards matches:</strong><br>
                <% outdoor_matches.each do |angler| %>
                    <%= '✓' if @scores.find(score.id).co_angler_id == angler.user.id %>
                    <%= link_to "#{angler.first_name} #{angler.last_name}", "/scores/co_angler/#{score.id}/#{angler.user.id}" %><br>
                <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

<%= form_tag import_scores_path, multipart: true do %>
    <%= select_tag 'event', options_from_collection_for_select(@events, 'id', 'name_and_date') %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import' %>
<% end %>
</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<div class="navbar well">
    <%= link_to "&larr; Back to Event".html_safe, "/scores/?event_id=#{@score.event_id}" %>
</div>
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @score.event.name_and_date+" (#{@score.event_id})" %>
</p>

<p>
  <strong>Position:</strong>
  <%= @score.position %>
</p>

<p>
  <strong>Angler:</strong>
  <%= @score.angler %>
</p>

<p>
  <strong>Angler rewards:</strong>
  <%= @score.angler_rewards %>
</p>

<p>
  <strong>Co angler:</strong>
  <%= @score.co_angler %>
</p>

<p>
  <strong>Co angler rewards:</strong>
  <%= @score.co_angler_rewards %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @score.weight %>
</p>

<p>
  <strong>Bf:</strong>
  <%= @score.bf %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @score.hp %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>
</div>