config/routes.rb
BpsFishingTour::Application.routes.draw do

    resources :scores do
        collection { post :import }
    end
    get 'scores/angler/:id/:angler_id' => 'scores#angler'
    get 'scores/co_angler/:id/:co_angler_id' => 'scores#co_angler'
    get '/score/remove-angler' => 'scores#remove_angler'
    get 'score/remove-co-angler' => 'scores#remove_co_angler'

    # Static Page Routing
    root to: 'static_pages#home'
    %w[thanks about confirm help].each do |page|
        get page, controller: 'static_pages', action: page
    end

    get '/select_profile_picture' => 'profiles#select_profile_pic'
    post '/upload_profile_pic' => 'profiles#upload_profile_pic'
    get'/team_select_profile_picture' => 'teams#select_profile_pic'
    post '/upload_team_pic' => 'teams#upload_team_pic'
    # Profile Routing
    get '/myprofile' => 'profiles#show_current', as: 'my_profile'
    get '/profiles', to: redirect('/anglers')
    get '/profiles/completion-reminder' => 'profiles#completion_reminder'
    resources :profiles


    # Event Routing
    resources :events
    match '/events/:id/attend' => 'events#register_event', as: 'register_event', via: :post
    match '/events/:id/unattend' => 'events#unregister_event', as: 'unregister_event', via: :post
    get '/events' => 'events#index', as: 'events_path'
    get '/event-scores/:id' => 'events#event_scores', as: :event_scores, via: :get
    post '/events/:id/merge' => 'events#merge', as: :event_merge, via: :post
    # Authentication Routing
    devise_for :users, controllers: {
        registrations: 'registrations',
        confirmations: 'confirmations'
    }

    get '/join', to: redirect('/users/sign_up')

    # Team Routing
    get '/teams', to: redirect('/leaderboard')
    match '/teammate/send_invite' => 'teams/requests#send_invite', as: 'send_invite', via: :post
    match '/teammate/invite_response/:id' => 'teams/requests#respond_to_invite', as: 'invite_response', via: :get
    match '/teammate/accept_invite/:request_id' => 'teams/requests#accept_invitation', as: 'accept_invite', via: :get
    match '/teammate/reject_invite' => 'teams/requests#reject_invitation', as: 'reject_invite', via: :get

    match '/users/:id/team_invitations' => 'teams/requests#team_invitations', as: 'team_invitations', via: :get
    scope '/teams' do
        match '/requests/new' => 'teams/requests#new', via: :get
        get '/requests/invite-reminder' => 'teams/requests#invite_reminder'
    end

    resources :teams

    # Anglers Routing
    get '/anglers' => 'anglers#index'

    # Leaderboard Routing
    get '/leaderboard' => 'leaderboard#index'

    # News Routing
    get '/news' => 'news#index'
    get '/news/:year/:month/:day/:title' => 'news#story'

    # Secret Admin Routing
    get '/admin/users-report' => 'admin#users_report'
    get '/admin/users-table' => 'admin#users_table', as: 'user_report'
    get '/admin/team-table' => 'admin#team_table', as: 'team_table'
end

app/views/notifications/add_name_to_profile.html.erb
<div class="alert alert-block alert-error">
    <p><strong>We need to know your name!</strong></p>
    <p>In order to show up on the <%= link_to 'leaderboard', leaderboard_path %> or on the <%= link_to 'list of anglers', anglers_path %>, we need you to provide us with your first and last name.  Please head to the "My Account" tab on <%= link_to 'your profile page', my_profile_path %> and fill in your information.</p>
</div>

app/views/notifications/add_outdoor_rewards_to_profile.html.erb
<div class="alert alert-block alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><strong>We need to know your Outdoor Rewards number</strong></p>
    <p>In order to be eligible to win, we need you to provide us with your outdoor rewards number.  Please head to the "My Account" tab on <%= link_to 'your profile page', my_profile_path %> and fill in your information.</p>
</div>

app/views/notifications/remind_your_teammate_to_accept.html.erb
<div class="alert alert-block alert-error">
    <p><strong>You need a teammate!</strong></p>
    <p>In order to show up on the <%= link_to 'leaderboard', leaderboard_path %> or <%= link_to 'sign up for events', events_path %>, your teammate must accept your invitation to officially be paired together. Our records show this step hasn't been completed.  If you wish to re-send their teammate request, head over to the <%= link_to 'teammate request form', requests_new_path %>.</p>
</div>

app/views/notifications/request_a_teammate.html.erb
<div class="alert alert-block alert-error">
    <p><strong>You need a teammate!</strong></p>
    <p>In order to show up on the <%= link_to 'leaderboard', leaderboard_path %> or <%= link_to 'sign up for events', events_path %>, we need you to request a teammate.  Please input the email address of your desired teammate into the <%= link_to 'teammate request form', requests_new_path %>.</p>
</div>

app/views/notifications/sign_up_for_an_event.html.erb
<div class="alert alert-block alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><strong>Sign up for an event</strong></p>
    <p>In order to show up on the <%= link_to 'leaderboard', leaderboard_path %>, your team must compete in an event.  Please head to the <%= link_to 'Tour Events', events_path %> page, and sign up for an event.</p>
</div>