config/routes.rb
BpsFishingTour::Application.routes.draw do

    resources :scores do
        collection { post :import }
    end
    get 'scores/angler/:id/:angler_id' => 'scores#angler'
    get 'scores/co_angler/:id/:co_angler_id' => 'scores#co_angler'
    get '/score/remove-angler' => 'scores#remove_angler'
    get 'score/remove-co-angler' => 'scores#remove_co_angler'

    # Static Page Routing
    root to: 'static_pages#home'
    %w[thanks about confirm help].each do |page|
        get page, controller: 'static_pages', action: page
    end

    get '/select_profile_picture' => 'profiles#select_profile_pic'
    post '/upload_profile_pic' => 'profiles#upload_profile_pic'
    get'/team_select_profile_picture' => 'teams#select_profile_pic'
    post '/upload_team_pic' => 'teams#upload_team_pic'
    # Profile Routing
    get '/myprofile' => 'profiles#show_current', as: 'my_profile'
    get '/profiles', to: redirect('/anglers')
    get '/profiles/completion-reminder' => 'profiles#completion_reminder'
    resources :profiles


    # Event Routing
    resources :events
    match '/events/:id/attend' => 'events#register_event', as: 'register_event', via: :post
    match '/events/:id/unattend' => 'events#unregister_event', as: 'unregister_event', via: :post
    get '/events' => 'events#index', as: 'events_path'
    get '/event-scores/:id' => 'events#event_scores', as: :event_scores, via: :get
    post '/events/:id/merge' => 'events#merge', as: :event_merge, via: :post
    # Authentication Routing
    devise_for :users, controllers: {
        registrations: 'registrations',
        confirmations: 'confirmations'
    }

    get '/join', to: redirect('/users/sign_up')

    # Team Routing
    get '/teams', to: redirect('/leaderboard')
    match '/teammate/send_invite' => 'teams/requests#send_invite', as: 'send_invite', via: :post
    match '/teammate/invite_response/:id' => 'teams/requests#respond_to_invite', as: 'invite_response', via: :get
    match '/teammate/accept_invite/:request_id' => 'teams/requests#accept_invitation', as: 'accept_invite', via: :get
    match '/teammate/reject_invite' => 'teams/requests#reject_invitation', as: 'reject_invite', via: :get

    match '/users/:id/team_invitations' => 'teams/requests#team_invitations', as: 'team_invitations', via: :get
    scope '/teams' do
        match '/requests/new' => 'teams/requests#new', via: :get
        get '/requests/invite-reminder' => 'teams/requests#invite_reminder'
    end

    resources :teams

    # Anglers Routing
    get '/anglers' => 'anglers#index'

    # Leaderboard Routing
    get '/leaderboard' => 'leaderboard#index'

    # News Routing
    get '/news' => 'news#index'
    get '/news/:year/:month/:day/:title' => 'news#story'

    # Secret Admin Routing
    get '/admin/users-report' => 'admin#users_report'
    get '/admin/users-table' => 'admin#users_table', as: 'user_report'
    get '/admin/team-table' => 'admin#team_table', as: 'team_table'
end

app/models/event.rb
class Event < ActiveRecord::Base
    has_and_belongs_to_many :divisions
    has_and_belongs_to_many :teams
    has_many :scores


    validates :name, :date, :presence => true

    default_scope {
        order('date ASC')
    }

    def name_and_date
        "#{self.name} #{self.date}"
    end

    # Used to merge the event passed in into the calling event
    def merge(event, destroy = true)
        begin
            #merge scores
            raise if !self.scores.empty? && !event.scores.empty?
            event.scores.each do |score|
                score.update(event_id: self.id)
            end
        rescue
            return false
        end

        #merge divisions if applicable
        event.divisions.each do |division|
            division.events << self unless division.events.include?(self)
        end

        #merge teams
        event.teams.each do |team|
            self.teams << team unless self.teams.include?(team)
        end

        Event.destroy(event.id) if destroy
    end

    def merge_into(event)
        event.merge(self)
    end

    def possible_duplicates
        @event = self
        return Event.where("name LIKE ?", @event.name).where.not("date > ?", (@event.date+1.day).to_s(:db)).where.not("date < ?", (@event.date-1.day+1.day).to_s(:db)).where.not(id: @event.id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.order('date')
    @divisions = Division.all
    @board = Leaderboard.qualified_teams
  end

  # GET /events/1
  def show
    if(current_user.teams.size > 0 && current_user.teammate)
      @can_register = true
    else
      @can_register = false
    end
  end

  def event_scores
    @fullads = true
    @scores = Score.where(event_id: params[:id]).order("position ASC")
    # render text: @scores.inspect
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def register_event
    event = Event.find params[:id]
    if !current_user.my_team.events.include? event
      current_user.my_team.events << event
      flash[:register_event] = "Your team is now registered to participate in #{event.name}!"
      #Email them Here
      RegisterEventMailer.event_registered(event, current_user).deliver
    else
      flash[:alreay_registered_event] = "Your team is already registered to attend this event!"
    end
    redirect_to my_profile_path
  end

  def unregister_event
    event = Event.find params[:id]
    current_user.my_team.events.delete(event)
    flash[:unregister_event] = "Your team is now unregistered from #{event.name}!"
    redirect_to my_profile_path
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
    end
  end

  # GET /events/1/merge
  def merge
    #render text: params
    @event = Event.find(params[:id]) unless Event.where(id: params[:id]).empty?
    @event.merge(Event.find(params[:merge_event_id])) unless Event.where(id: params[:merge_event_id]).empty?
    redirect_to :back, notice: "Merged Events"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :address, :address2, :city, :province, :state, :country, :start_date, :end_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def add_status(team, event)
        score = team.event_score(event)
        return "#{pluralize(score, "point")}" if score
        return "Processing" if event.date.past?
        return "Coming Soon"
    end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/event_scores.html.erb
<%= render "shared/ads_bps" %>
<div id="eventScoresContainer">
	<div class="staticContainer">
		<div class='staticTopBar topBlue'>
			<h1> <%= Event.find(params[:id]).name %> Rankings</h1>
		</div>
		<div class='eventScoreInnerContainer'>
			<div class='alert'>*If while reviewing the rankings table you come across inaccurate information, please contact us at <a href="mailto:support@bassprofishingtour.com?subject=Bass Pro Fishing Tour Question" id="contact-us">support@bassprofishingtour.com</a> so we can make the proper corrections.</div> 
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Rank</th>
						<th>Angler</th>
						<th>Co-Angler</th>
						<th>Weight</th>
						<th>BF</th>
						<th>HP</th>
					</tr>
				</thead>
				<tbody>
					<% @scores.each do |score| %>
						<tr>
							<td> <%= score.position %> </td>
							<td> <%= score.angler_id.present? ? link_to(score.angler_user.full_name.upcase, profile_path(score.angler_user.profile.id)) : score.angler %> </td>
							<td> <%= score.co_angler_id.present? ? link_to(score.co_angler_user.full_name.upcase, profile_path(score.co_angler_user.profile.id)) : score.co_angler %> </td>
							<td> <%= '%.2f' % score.weight if score.weight %> </td>
							<td> <%= score.bf %> </td>
							<td> <%= score.hp %> </td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<% content_for :leaderboard do %>
    <div class="standingsLogo">
        <%= image_tag 'standingsBackground.png', alt: 'Standings' %>
        <div class="standingsText">
            <h2>Standings</h2>
            <%= render 'leaderboard/team_scores_mini' %>
            <%= link_to "Full Leaderboard", leaderboard_path %>
        </div>
    </div>
<% end %>

<div id="eventContainer">
    <div class="eventContainer">
        <div class="findAnEvent">
            <%= render_notification %>

            <div class="findAnEventText"><h2>FIND AN EVENT</h2></div>
            <div class="findAnEventSmall"><h2>Ontario, Canada Region</h2></div>
            <p>The Ontario Region of the Bass Pro Shops Fishing Tour features all 2013 CSFL tournaments as sanctioned qualifying events. Use the left and right arrows below to scroll through each CSFL division and add events to your Bass Pro Shops Fishing Tour.</p>

        </div>
        <div class="bassEventMap">
            <div id="slideshowMap" class="carousel slide">
                <div id="slidesContainer" class="carousel-inner">
                    <% @divisions.select { |division| division.events.present? }.each_with_index do |division, index| %>
                        <div class="item <%= 'active' if index == 0 %>" data-division="<%= division.id %>">
                            <%= image_tag 'mapOntario.png', alt: 'Ontario', class: 'mapOntario' %>
                            <h2 class="mapTextContainer">
                                CSFL BassMania (BM)
                                <hr>
                                <%= division.name %>
                            </h2>
                        </div>
                    <% end %>
                </div>
                <a class="control left" href='#slideshowMap' data-slide="prev"><%= image_tag 'icons/previous.png', alt: 'Previous Division' %></a>
                <a class="control right" href='#slideshowMap' data-slide="next"><%= image_tag 'icons/next.png', alt: 'Next Division' %></a>
                <ol class="carousel-indicators">
                    <% @divisions.select { |division| division.events.present? }.count.times do |index| %>
                        <li data-target="#slideshowMap" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
                    <% end %>
                </ol>
            </div>
        </div>
        <% @events.each do |event| %>
            <div class="bassAttendBG">
                <div class="bassEventAttendBackground" data-division="<%= event.divisions.map { |division| division.id }.join(' ') %>">
                    <div class="bassEventAttendText">
                        <div class="rankingsButton"> <%= button_to 'Rankings', event_scores_path(event.id), method: :get, class: :seeRankButton if Score.where(event_id: event.id).length > 0 %> </div>
                        <div class="bassET"><h2><%= event.name %></h2></div>
                        <div class="bassET">
                            <p><%= "#{event.city}, #{ event.province || event.state } #{event.country} #{event.postal_code}" %></p>
                            <p><%= "#{event.date.to_date.to_formatted_s :long}" %></p>
                        </div>
                    </div>
                    <% if user_signed_in? && current_user.my_team %>
                        <div class="actions-container">
                            <p class="is-fishing"><%= event.date >= Time.now ? 'Is your team fishing in this event?':'Did your team fish in this event?' %></p>
                            <div class="yesNoContainer">
                                    <% if current_user.my_team.events.include?(event) %>
                                        <%= image_tag 'iconCheck.png', class: "ifYes" , alt: 'Check Mark' %>
                                    <% end %>

                                    <%= button_to "Yes", register_event_path(event), class: 'enterEventButton' %>

                                    <% if !current_user.my_team.events.include?(event) %>
                                        <%= image_tag 'iconCheck.png', class: "ifNo", alt: 'Check Mark' %>
                                        <%= button_to "No", unregister_event_path(event), class: 'noEventButton' %>
                                    <% else %>
                                        <%= button_to "No", unregister_event_path(event), class: 'noEventButton deemphasized' %>
                                    <% end %>

                            </div>
                        </div>
                    <% else %>
                        <div class="actions-container">
                            <%= link_to event.date > Time.now ? "Sign up and register your team to attend." : "Sorry you missed this event. Sign up and register your team for future events." , new_user_registration_path, class: "is-fishing"%>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="findAnEvent">
    <div class="findAnEventText"><h2>FIND AN EVENT</h2></div>
</div>
<div class="bassEventEnter">
    <div class="bassEventEnterBackground">
        <div class="bassEventEnterContainer">
            <%= image_tag 'eventEnterPicture.jpg', class: 'eventEnterPic', alt: 'Event Picture' %>
            <div class="bassEventEnterText">
                <h2><%= @event.name %></h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula porta felis euismod semper. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula porta felis euismod semper. Cras justo odio, dapibus ac facilisis in, egestas eget quam. onec id elit non mi porta gravida at eget metus. </p>
                <% if @can_register %>
                <h1>Are you fishing this event?</h1>
                  <%= button_to "Yes", register_event_path(@event), class: 'enterEventButton', method: :post %>
                  <%= button_to "No", '#', class: 'noEventButton', method: :post %>
                <% else %>
                  <h1>You Must Find a Teammate in Order to Register this Event</h1>
                <% end %>
            </div>
        </div>
    </div>
</div>